export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';
export const LOAD_USER_FAIL = 'LOAD_USER_FAIL';

export const LOGOUT = 'LOGOUT';

export const CHECK_USER = 'CHECK_USER';

export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PROJECTS = 'GET_PROJECTS';
export const GET_SERVICES = 'GET_SERVICES';

export const ADD_PRODUCTS = 'ADD_PRODUCTS';
export const ADD_PROJECTS = 'ADD_PROJECTS';
export const ADD_SERVICES = 'ADD_SERVICES';

export const EDIT_PRODUCTS = 'EDIT_PRODUCTS';
export const EDIT_PROJECTS = 'EDIT_PROJECTS';
export const EDIT_SERVICES = 'EDIT_SERVICES';

export const DELETE_PRODUCTS = 'DELETE_PRODUCTS';
export const DELETE_PROJECTS = 'DELETE_PROJECTS';
export const DELETE_SERVICES = 'DELETE_SERVICES';

export const ESTEEM_DATA = 'ESTEEM_DATA';
export const ESTEEM_ALL = 'ESTEEM_ALL';
export const ESTEEM_SAVE_STORE = 'ESTEEM_SAVE_STORE';
